package com.example.demo.util;

import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class Contants {
	public static String DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)";
	public static Map<String, String> SPECIAL_CASES = Stream.of(new String[][] { { "ee", "et" } })
			.collect(Collectors.toMap(data -> data[0], data -> data[1]));
	

	public static Map<String, String> LANGUAGES =  Stream.of(new String[][] {
	    {"af", "afrikaans"},
	    {"sq", "albanian"},
	    {"am", "amharic"},
	    {"ar", "arabic"},
	    {"hy", "armenian"},
	    {"az", "azerbaijani"},
	    {"eu", "basque"},
	    {"be", "belarusian"},
	    {"bn", "bengali"},
	    {"bs", "bosnian"},
	    {"bg", "bulgarian"},
	    {"ca", "catalan"},
	    {"ceb", "cebuano"},
	    {"ny", "chichewa"},
	    {"zh-cn", "chinese (simplified)"},
	    {"zh-tw", "chinese (traditional)"},
	    {"co", "corsican"},
	    {"hr", "croatian"},
	    {"cs", "czech"},
	    {"da", "danish"},
	    {"nl", "dutch"},
	    {"en", "english"},
	    {"eo", "esperanto"},
	    {"et", "estonian"},
	    {"tl", "filipino"},
	    {"fi", "finnish"},
	    {"fr", "french"},
	    {"fy", "frisian"},
	    {"gl", "galician"},
	    {"ka", "georgian"},
	    {"de", "german"},
	    {"el", "greek"},
	    {"gu", "gujarati"},
	    {"ht", "haitian creole"},
	    {"ha", "hausa"},
	    {"haw", "hawaiian"},
	    {"iw", "hebrew"},
	    {"hi", "hindi"},
	    {"hmn", "hmong"},
	    {"hu", "hungarian"},
	    {"is", "icelandic"},
	    {"ig", "igbo"},
	    {"id", "indonesian"},
	    {"ga", "irish"},
	    {"it", "italian"},
	    {"ja", "japanese"},
	    {"jw", "javanese"},
	    {"kn", "kannada"},
	    {"kk", "kazakh"},
	    {"km", "khmer"},
	    {"ko", "korean"},
	    {"ku", "kurdish (kurmanji)"},
	    {"ky", "kyrgyz"},
	    {"lo", "lao"},
	    {"la", "latin"},
	    {"lv", "latvian"},
	    {"lt", "lithuanian"},
	    {"lb", "luxembourgish"},
	    {"mk", "macedonian"},
	    {"mg", "malagasy"},
	    {"ms", "malay"},
	    {"ml", "malayalam"},
	    {"mt", "maltese"},
	    {"mi", "maori"},
	    {"mr", "marathi"},
	    {"mn", "mongolian"},
	    {"my", "myanmar (burmese)"},
	    {"ne", "nepali"},
	    {"no", "norwegian"},
	    {"ps", "pashto"},
	    {"fa", "persian"},
	    {"pl", "polish"},
	    {"pt", "portuguese"},
	    {"pa", "punjabi"},
	    {"ro", "romanian"},
	    {"ru", "russian"},
	    {"sm", "samoan"},
	    {"gd", "scots gaelic"},
	    {"sr", "serbian"},
	    {"st", "sesotho"},
	    {"sn", "shona"},
	    {"sd", "sindhi"},
	    {"si", "sinhala"},
	    {"sk", "slovak"},
	    {"sl", "slovenian"},
	    {"so", "somali"},
	    {"es", "spanish"},
	    {"su", "sundanese"},
	    {"sw", "swahili"},
	    {"sv", "swedish"},
	    {"tg", "tajik"},
	    {"ta", "tamil"},
	    {"te", "telugu"},
	    {"th", "thai"},
	    {"tr", "turkish"},
	    {"uk", "ukrainian"},
	    {"ur", "urdu"},
	    {"uz", "uzbek"},
	    {"vi", "vietnamese"},
	    {"cy", "welsh"},
	    {"xh", "xhosa"},
	    {"yi", "yiddish"},
	    {"yo", "yoruba"},
	    {"zu", "zulu"},
	    {"fil", "Filipino"},
	    {"he", "Hebrew"}
	}).collect(Collectors.toMap(data -> data[0], data -> data[1]));

	public static Map<String, String> LANGCODES = 
			LANGUAGES.entrySet()
		       .stream()
		       .collect(Collectors.toMap(Map.Entry::getValue, Map.Entry::getKey));
	public static String BASE = "https://translate.google.com";
//	public static String TRANSLATE = "https://{host}/translate_a/single";
	public static String TRANSLATE = "https://{host}/translate_a/single";
}
